#!/usr/bin/env php
<?php include __DIR__.'/vendor/autoload.php';

use RestCord\DiscordClient;



$_CONFIG = array_merge(
	require __DIR__.'/config/main.php',
	require __DIR__.'/config/token.php',
	require __DIR__.'/config/channel.php'
);



$discord = new DiscordClient(['token' => $_CONFIG['token']]); 


echo "runned\n\n";

