#!/usr/bin/env php
<?php session_start();

include __DIR__.'/models/Script.php';

/*
 *	application setup starts
 */

$_SESSION['_CONFIG'] = $_CONFIG = array_merge(
	require __DIR__.'/config/main.php',
	require __DIR__.'/config/token.php',
	require __DIR__.'/config/channel.php'
);

/*
 *	run application
 */
$run = new Script();
